source 'https://rubygems.org'

gem 'sinatra'
#Sql gem
gem 'mysql'
#Crawler gems
gem 'nokogiri'
#Web server gem for sinatra. Set up config file
gem 'shotgun'

gem 'sqlite3'

gem 'restart'

#Sidekiq gem to run background jobs
gem 'sidekiq'
#Redis Sever
gem 'redis'

gem 'haversine'

gem "geocoder", git: "git://github.com/alexreisner/geocoder.git"

gem 'rake'

gem 'sinatra-activerecord'
